# Latex: https://github.com/marketplace/actions/github-action-for-latex, GH release: https://github.com/softprops/action-gh-release
name: Build pdf in GitHub and upload to release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile latex presentations
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_shell_escape: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.pdf
          tag_name: report.pdf